const express = require('express');
const prisma = require('../db');
const authMiddleware = require('../middleware/auth');
const { getValidToken } = require('../utils/tokenHelper');
const { createPlaylist, addTracksToPlaylist } = require('../utils/spotify');

const router = express.Router();

/**
 * POST /api/playlists/create
 * Creates a Spotify playlist under the host's profile containing the lobby's winning tracks.
 */
router.post('/create', authMiddleware, async (req, res) => {
  const { lobbyId } = req.body;
  const requesterId = req.user.userId; // host spotify ID

  if (!lobbyId) {
    return res.status(400).json({ error: 'Lobby ID is required' });
  }

  try {
    // 1. Fetch lobby, users, and tracks
    const lobby = await prisma.lobby.findUnique({
      where: { id: lobbyId },
      include: {
        users: true,
        tracks: {
          include: {
            swipes: true
          }
        }
      }
    });

    if (!lobby) {
      return res.status(404).json({ error: 'Lobby not found' });
    }

    // 2. Validate host and permission
    const host = lobby.users.find(u => u.role === 'HOST');
    if (!host) {
      return res.status(400).json({ error: 'Lobby has no host registered' });
    }

    if (host.id !== requesterId) {
      return res.status(403).json({ error: 'Only the lobby Host can export the playlist.' });
    }

    const userCount = lobby.users.length;
    if (userCount === 0) {
      return res.status(400).json({ error: 'No users found in lobby' });
    }

    // 3. Calculate matched tracks
    // A track is a 100% match if liked swipes equal userCount
    let matchedTracks = lobby.tracks.filter(track => {
      const likesCount = track.swipes.filter(s => s.liked).length;
      return likesCount === userCount;
    });

    let matchRate = '100%';

    // If no 100% matches exist, fall back to diluted match (e.g. >= 80% agreement)
    if (matchedTracks.length === 0) {
      const threshold = Math.ceil(userCount * 0.8);
      matchedTracks = lobby.tracks.filter(track => {
        const likesCount = track.swipes.filter(s => s.liked).length;
        return likesCount >= threshold && likesCount > 0;
      });
      matchRate = '>=80%';
    }

    // If still no matches, fall back to any track liked by at least one person
    if (matchedTracks.length === 0) {
      matchedTracks = lobby.tracks.filter(track => {
        const likesCount = track.swipes.filter(s => s.liked).length;
        return likesCount > 0;
      });
      matchRate = '>0%';
    }

    if (matchedTracks.length === 0) {
      return res.status(400).json({ error: 'No songs were liked by anyone. Cannot create playlist.' });
    }

    // 4. Get host valid token
    const accessToken = await getValidToken(host.id);

    // 5. Create playlist on Spotify
    const playlistName = `MusicMap - Room ${lobbyId}`;
    const playlistDescription = `Generated by MusicMap! Tracks matched at ${matchRate} agreement level. Total users: ${userCount}.`;
    
    const spotifyPlaylist = await createPlaylist(
      accessToken,
      host.id,
      playlistName,
      playlistDescription
    );

    // 6. Add tracks to playlist
    const trackSpotifyIds = matchedTracks.map(t => t.spotifyId);
    await addTracksToPlaylist(accessToken, spotifyPlaylist.id, trackSpotifyIds);

    res.json({
      success: true,
      playlistName,
      playlistId: spotifyPlaylist.id,
      url: spotifyPlaylist.external_urls.spotify,
      tracksCount: matchedTracks.length,
      matchRate
    });
  } catch (err) {
    console.error('Failed to create Spotify playlist:', err.response?.data || err.message);
    res.status(500).json({
      error: 'Failed to create playlist on Spotify. Please ensure Host permissions are still valid.'
    });
  }
});

module.exports = router;
